### ISSUE TITLE
Error when running first time

### ISSUE THREAD

**Issue by roelvde** [salimane/cryptodiversify#1]
Just installed a fresh version, put in my API keys and fired it up. 
It throws me this error: 

Tried debugging myself but could not find it.

`2018-06-26 20:06:05,352][PortfolioUpdater][portfolio][   ERROR] Exception in requesting portfolio: <type 'exceptions.KeyError'> portfolio.py: 45
[2018-06-26 20:06:05,352][PortfolioUpdater][portfolio][ WARNING] No data from web source. Loading file
Exception in thread PortfolioUpdater:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/rvde/Desktop/cryptodiversify/cryptodiversify/bot.py", line 80, in __PortfolioUpdater
    self.__portfolio_obj.get_portfolio(),
  File "/Users/rvde/Desktop/cryptodiversify/cryptodiversify/portfolio.py", line 26, in get_portfolio
    return self.__initialize_portfolio()
  File "/Users/rvde/Desktop/cryptodiversify/cryptodiversify/portfolio.py", line 73, in __initialize_portfolio
    portfolio = json.load(f)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 290, in load
    **kw)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
`

**Comment by salimane** [comment]
@roelvde make sure you have the latest version of the repo:
```
git clone https://github.com/salimane/cryptodiversify.git
cd cryptodiversify
git pull
git describe
```
I have pushed a fix for this type of errors 10 days ago.

Please report back if you are still seeing the same errors

Thanks

**Comment by roelvde** [comment]
I have it working now! Couldn't run it from a desktop folder. Still learning ;) !
